#**********************************************************
#* CATEGORY    SENSORS
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright (C) 2017  Haynie Research & Development

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License along
#with this program; if not, write to the Free Software Foundation, Inc.,
#51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - wind_speed
    - cloud_cover
    - hourly_summary
    - daily_summary

- platform: wunderground
  api_key: !secret wunderground_key
  monitored_conditions:
    - weather
    - temp_f
    - pressure_in
    - wind_string
    - relative_humidity
    - alerts

- platform: template
  sensors:
    home_address:
      value_template: !secret home_address

    jarvis_greeting:
      value_template: '{% if is_state("sensor.random_4", "1") %}Pardon me{% elif is_state("sensor.random_4", "2") %}Pardon the interruption{% elif is_state("sensor.random_4", "3") %}Excusez-moi{% elif is_state("sensor.random_4", "4") %}Pardon{% else %}Excuse me{% endif %}'

    hue_bridge:
      friendly_name: 'Hue Bridge'
      value_template: '{% if is_state("device_tracker.hue_bridge", "home") %}Online{% else %}Offline{% endif %}'

    wink_relay_upstairs_hall:
      friendly_name: 'Wink Relay - Upstairs Hallway'
      value_template: '{% if is_state("device_tracker.wink_relay_upstairs_hall", "home") %}Online{% else %}Offline{% endif %}'

    jarvis_repeater:
      friendly_name: 'JARVIS Repeater'
      value_template: '{% if is_state("device_tracker.jarvis_repeater", "home") %}Online{% else %}Offline{% endif %}'

    wink_relay_wesley:
      friendly_name: 'Wink Relay - Wesley'
      value_template: '{% if is_state("device_tracker.wink_relay_wesley", "home") %}Online{% else %}Offline{% endif %}'

    wink_relay_master_bed:
      friendly_name: 'Wink Relay - Master Bedroom'
      value_template: '{% if is_state("device_tracker.wink_relay_master_bed", "home") %}Online{% else %}Offline{% endif %}'

    wink_relay_hudson:
      friendly_name: 'Wink Relay - Hudson'
      value_template: '{% if is_state("device_tracker.wink_relay_hudson", "home") %}Online{% else %}Offline{% endif %}'

    synology_nas:
      friendly_name: 'Synology NAS'
      value_template: '{% if is_state("device_tracker.synology_nas", "home") %}Online{% else %}Offline{% endif %}'

    lances_imac:
      friendly_name: 'Lances iMac'
      value_template: '{% if is_state("device_tracker.lances_imac", "home") %}Online{% else %}Offline{% endif %}'

    harmony_hub_living_room:
      friendly_name: 'Harmony Hub - Living Room'
      value_template: '{% if is_state("device_tracker.harmony_hub_living_room", "home") %}Online{% else %}Offline{% endif %}'

    honeywell_thermostat_1:
      friendly_name: 'Honeywell Thermostat 1'
      value_template: '{% if is_state("device_tracker.honeywell_thermostat_1", "home") %}Online{% else %}Offline{% endif %}'

    honeywell_thermostat_2:
      friendly_name: 'Honeywell Thermostat 2'
      value_template: '{% if is_state("device_tracker.honeywell_thermostat_2", "home") %}Online{% else %}Offline{% endif %}'

    airport_extreme:
      friendly_name: 'Airport Extreme'
      value_template: '{% if is_state("device_tracker.airport_extreme", "home") %}Online{% else %}Offline{% endif %}'

    airport_express:
      friendly_name: 'Airport Express'
      value_template: '{% if is_state("device_tracker.airport_express", "home") %}Online{% else %}Offline{% endif %}'

    epson_wf3540:
      friendly_name: 'Epson WF3540'
      value_template: '{% if is_state("device_tracker.epson_wf3540", "home") %}Online{% else %}Offline{% endif %}'

    wink_hub:
      friendly_name: 'Wink Hub'
      value_template: '{% if is_state("device_tracker.wink_hub", "home") %}Online{% else %}Offline{% endif %}'

    tpl_hudson_repeater:
      friendly_name: 'TPL - Hudson Repeater'
      value_template: '{% if is_state("device_tracker.tpl_hudson_repeater", "home") %}Online{% else %}Offline{% endif %}'

    wink_relay_kitchen:
      friendly_name: 'Wink Relay - Kitchen'
      value_template: '{% if is_state("device_tracker.wink_relay_kitchen", "home") %}Online{% else %}Offline{% endif %}'

    play_station_3:
      friendly_name: 'PlayStation 3'
      value_template: '{% if is_state("device_tracker.play_station_3", "home") %}Online{% else %}Offline{% endif %}'

    play_station_4:
      friendly_name: 'PlayStation 4'
      value_template: '{% if is_state("device_tracker.play_station_4", "home") %}Online{% else %}Offline{% endif %}'

    living_room_tv:
      friendly_name: 'Living Room TV'
      value_template: '{% if is_state("device_tracker.living_room_tv", "home") %}Online{% else %}Offline{% endif %}'

    katies_laptop:
      friendly_name: 'Katies Laptop'
      value_template: '{% if is_state("device_tracker.katies_laptop", "home") %}Online{% else %}Offline{% endif %}'

    citi_laptop:
      friendly_name: 'Citi Laptop'
      value_template: '{% if is_state("device_tracker.citi_laptop", "home") %}Online{% else %}Offline{% endif %}'

    lances_ipad:
      friendly_name: 'Lances iPad'
      value_template: '{% if is_state("device_tracker.lances_ipad", "home") %}Online{% else %}Offline{% endif %}'

    livingroom_harmony:
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'

    average_up_temp:
      friendly_name: 'Average Upstairs Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_temperature.state) + float(states.climate.upstairs.attributes.current_temperature) + float(states.sensor.hudsons_room_temperature.state) + float(states.sensor.wesleys_room_temperature.state)) / 4) | round(0) }}

    average_down_temp:
      friendly_name: 'Average Downstairs Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.kitchen_temperature.state) + float(states.sensor.master_bedroom_temperature.state) + float(states.climate.downstairs.attributes.current_temperature)) / 3) | round(0) }}

    average_home_temp:
      friendly_name: 'Average Home Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_temperature.state) + float(states.climate.upstairs.attributes.current_temperature) + float(states.sensor.kitchen_temperature.state) + float(states.sensor.master_bedroom_temperature.state) + float(states.climate.downstairs.attributes.current_temperature) + float(states.sensor.hudsons_room_temperature.state) + float(states.sensor.wesleys_room_temperature.state)) / 7) | round(0) }}

    average_up_humid:
      friendly_name: 'Average Upstairs Humidity'
      unit_of_measurement: '%'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_humidity.state) + float(states.sensor.hudsons_room_humidity.state) + float(states.sensor.wesleys_room_humidity.state)) / 3) | round(0) }}

    average_down_humid:
      friendly_name: 'Average Downstairs Humdity'
      unit_of_measurement: '°%'
      value_template: >-
        {{ ((float(states.sensor.kitchen_humidity.state) + float(states.sensor.master_bedroom_humidity.state)) / 2) | round(0) }}

    average_home_humid:
      friendly_name: 'Average Home Humidity'
      unit_of_measurement: '°%'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_humidity.state) + float(states.sensor.kitchen_humidity.state) + float(states.sensor.master_bedroom_humidity.state) + float(states.sensor.hudsons_room_humidity.state) + float(states.sensor.wesleys_room_humidity.state)) / 5) | round(0) }}

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: rest
  scan_interval: 86400
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

- platform: command_line
  name: "Uptime"
  command: echo "$(($(date +%s) - $(date -d "$(head -n1 /opt/jarvis/home-assistant.log | cut -d' ' -f-2)" +%s)))"
  scan_interval: 720
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {{ '%02d' % hours }}:{{ '%02d' % minutes }}

- platform: command_line
  name: System volume
  command: /opt/jarvis/scripts/getvolume.sh
  unit_of_measurement: percent

- platform: command_line
  name: Day of Week
  command: /opt/jarvis/scripts/getdayofweek.sh

- platform: command_line
  name: Month
  command: /opt/jarvis/scripts/getmonth.sh

- platform: command_line
  name: Day
  command: /opt/jarvis/scripts/getday.sh

- platform: command_line
  name: Internet Status
  command: /opt/jarvis/scripts/internetstatus.sh

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: random
  name: random_outside_lights
  minimum: 1
  maximum: 6

- platform: random
  name: random_2
  minimum: 1
  maximum: 2

- platform: random
  name: random_3
  minimum: 1
  maximum: 3

- platform: random
  name: random_4
  minimum: 1
  maximum: 4

- platform: random
  name: random_5
  minimum: 1
  maximum: 5

- platform: random
  name: random_rules
  minimum: 1
  maximum: 50
