#**********************************************************
#* CATEGORY    HOME ASSISTANT AUTOMATION
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright (C) 2017  Haynie Research & Development

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License along
#with this program; if not, write to the Free Software Foundation, Inc.,
#51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#**********************************************************
# Upstairs Floorplan
#**********************************************************
name: Upstairs
image: /local/custom_ui/upstairs/upstairs.svg
stylesheet: /local/custom_ui/upstairs/upstairs.css
date_format: YYYY-MMM-DD
hide_app_toolbar:

groups:
  - name: Alarm Panel
    entities:
       - alarm_control_panel.home_alarm
    states:
      - state: 'armed_away'
        class: 'alarm-armed'
      - state: 'armed_home'
        class: 'alarm-armed'
      - state: 'disarmed'
        class: 'alarm-disarmed'

  - name: thermostats_temp
    entities:
      - climate.upstairs
    text_template: '${entity.attributes.current_temperature ? Math.ceil(entity.attributes.current_temperature) + "°": "undefined"}'
    class_template: 'return "static-temp";'

  - name: LeftPanel
    entities:
      - scene.tv_blue
      - script.game_timer
      - script.leaving_in_15_min
      - script.restart_jarvis_base
      - script.restart_jarvis_stt
      - script.restart_system
      - input_boolean.lancefirecall
    states:
      - state: 'on'
        class: 'button-panel-on'
      - state: 'off'
        class: 'button-panel-off'
    action:
      domain: scene
      service: turn_on

  - name: Switches
    entities:
      - switch.hudsons_fan
      - switch.hudsons_light
      - switch.wesleys_fan
      - switch.wesleys_light
      - switch.hudsontv
      - switch.upstairs_bathroom_main
      - switch.upstairs_hallway
      - switch.upstairs_lights
      - switch.wesleytv
    states:
      - state: 'on'
        class: 'light-on'
      - state: 'off'
        class: 'light-off'
    action:
      service: toggle

  - name: Alarm Binary Sensors
    entities:
      - binary_sensor.smoke_and_co_co_detected
      - binary_sensor.smoke_and_co_smoke_detected
    states:
      - state: 'off'
        class: 'protect-off'
      - state: 'on'
        class: 'protect-on'

  - name: text_data
    entities:
      - sensor.time
      - sensor.average_load_1m
      - sensor.average_load_5m
      - sensor.average_load_15m
      - sensor.external_ip
      - sensor.day_of_week
      - sensor.month
      - sensor.day
      - sensor.dark_sky_hourly_summary
      - sensor.internet_status
      - sensor.uptime
    text_template: '${entity.state ? entity.state : "undefined"}'
    class_template: 'return "static-text";'

  - name: text_percent
    entities:
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.average_up_humid
    text_template: '${entity.state ? Math.ceil(entity.state) + "%": "undefined"}'
    class_template: 'return "static-text";'

  - name: text_mbps
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
    text_template: '${entity.state ? Math.ceil(entity.state) + " Mbit/s": "undefined"}'
    class_template: 'return "static-text";'

  - name: text_ms
    entities:
      - sensor.speedtest_ping
    text_template: '${entity.state ? Math.ceil(entity.state) + " ms": "undefined"}'
    class_template: 'return "static-text";'

  - name: text_temperature
    entities:
      - sensor.average_home_temp
      - sensor.average_up_temp
    text_template: '${entity.state ? Math.ceil(entity.state) + "°": "undefined"}'
    class_template: 'return "static-temp";'

  - name: links
    entities:
      - weblink.home
